### API KEY USED FOR API-CALLS
api_key_users:
  -
    username: test_key_user
    name: Test key User
    role: API_KEY
    api_key: <%= ENV["API_KEY"] %>
# External authentication source
external_auth_url: "https://example.org/auth"

## dFile Parameters
dfile_base_url: <%= ENV["DFILE_BASE_URL"] %>
dfile_api_key: <%= ENV["DFILE_API_KEY"] %>
